import { initializeApp, getApps } from 'firebase/app';
import { getMessaging, getToken, onMessage, isSupported, deleteToken } from 'firebase/messaging';
import { supabase } from '@/integrations/supabase/client';
import { devLog, devError } from '@/utils/devLog';
import { toast } from 'sonner';


const config = {
  apiKey: import.meta.env.VITE_FIREBASE_API_KEY,
  authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,
  projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID,
  storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
  appId: import.meta.env.VITE_FIREBASE_APP_ID,
};

const VAPID_KEY = import.meta.env.VITE_FIREBASE_VAPID_KEY as string | undefined;

function isPreviewOrIframe(): boolean {
  try {
    if (window.self !== window.top) return true;
  } catch {
    return true;
  }
  const h = window.location.hostname;
  return (
    h.startsWith('id-preview--') ||
    h.startsWith('preview--') ||
    h.endsWith('.lovableproject.com') ||
    h.endsWith('.lovableproject-dev.com') ||
    h.endsWith('.beta.lovable.dev')
  );
}

let currentToken: string | null = null;
const FIREBASE_PUSH_SCOPE = '/firebase-cloud-messaging-push-scope/';

async function waitForServiceWorkerActivation(registration: ServiceWorkerRegistration): Promise<void> {
  const worker = registration.active || registration.waiting || registration.installing;
  if (!worker || worker.state === 'activated') return;

  await new Promise<void>((resolve, reject) => {
    const timeout = window.setTimeout(() => {
      worker.removeEventListener('statechange', onStateChange);
      reject(new Error('Firebase messaging service worker activation timed out.'));
    }, 10_000);

    const onStateChange = () => {
      if (worker.state === 'activated') {
        window.clearTimeout(timeout);
        worker.removeEventListener('statechange', onStateChange);
        resolve();
      } else if (worker.state === 'redundant') {
        window.clearTimeout(timeout);
        worker.removeEventListener('statechange', onStateChange);
        reject(new Error('Firebase messaging service worker became redundant.'));
      }
    };

    worker.addEventListener('statechange', onStateChange);
  });
}

export async function initWebPush(userId: string, onNotification?: () => void): Promise<string | null> {
  try {
    if (isPreviewOrIframe()) return null;
    if (!('Notification' in window)) return null;
    if (!(await isSupported())) return null;
    if (!config.apiKey || !VAPID_KEY) {
      devLog('[Push] Firebase web config missing');
      return null;
    }

    if (Notification.permission === 'default') {
      const perm = await Notification.requestPermission();
      if (perm !== 'granted') return null;
    } else if (Notification.permission !== 'granted') {
      return null;
    }

    if (!getApps().length) initializeApp(config);
    // Keep Firebase Messaging on its own narrow scope so it cannot replace the
    // root-scoped app-shell service worker generated by vite-plugin-pwa.
    const swUrl =
      `/firebase-messaging-sw.js?apiKey=${encodeURIComponent(config.apiKey!)}` +
      `&projectId=${encodeURIComponent(config.projectId!)}` +
      `&appId=${encodeURIComponent(config.appId!)}` +
      `&senderId=${encodeURIComponent(config.messagingSenderId!)}`;
    const registrations = await navigator.serviceWorker.getRegistrations();
    await Promise.all(
      registrations
        .filter(
          (registration) =>
            registration.scope === `${window.location.origin}/` &&
            (registration.active?.scriptURL.includes('/firebase-messaging-sw.js') ||
              registration.waiting?.scriptURL.includes('/firebase-messaging-sw.js') ||
              registration.installing?.scriptURL.includes('/firebase-messaging-sw.js')),
        )
        .map((registration) => registration.unregister()),
    );

    const reg = await navigator.serviceWorker.register(swUrl, { scope: FIREBASE_PUSH_SCOPE });
    // navigator.serviceWorker.ready only resolves for a registration whose scope
    // controls the current page. Firebase intentionally uses a narrow scope here,
    // so wait for this specific registration instead of the root document.
    await waitForServiceWorkerActivation(reg);
    const messaging = getMessaging();
    const token = await getToken(messaging, { vapidKey: VAPID_KEY, serviceWorkerRegistration: reg });
    if (!token) return null;

    // Claim through the SECURITY DEFINER RPC so a token previously associated
    // with another signed-in user on this device can be reassigned safely.
    const { error: tokenError } = await supabase.rpc('claim_push_token', {
      p_token: token,
      p_platform: 'web',
      p_device_info: { userAgent: navigator.userAgent },
    });
    if (tokenError) {
      throw new Error(`Could not save this device for push notifications: ${tokenError.message}`);
    }
    currentToken = token;

    onMessage(messaging, () => {
      onNotification?.();
    });

    return token;
  } catch (e) {
    devError('[Push] web init failed', e);
    throw e instanceof Error ? e : new Error('Web push registration failed');
  }
}

export async function disableWebPush() {
  try {
    if (currentToken) {
      await supabase.from('push_device_tokens').delete().eq('token', currentToken);
    }
    if (await isSupported()) {
      const messaging = getMessaging();
      await deleteToken(messaging).catch(() => {});
    }
    currentToken = null;
  } catch (e) {
    devError('[Push] web disable failed', e);
  }
}
