import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://bharat-sales-spark.lovable.app/');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Email Address' }).fill('A');
  await page.getByRole('textbox', { name: 'Email Address' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Email Address' }).fill('Abhishek.kvp2979@gmail.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('87654321');
  await page.getByRole('button', { name: 'Sign In as User' }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(4).click();
  await page.getByRole('link', { name: 'Beats' }).click();
  await page.getByRole('button', { name: 'Create New Beat' }).click();
  await page.getByRole('textbox', { name: 'Beat Name' }).fill('test');
  await page.getByLabel('Territory (Optional)').selectOption('1376ce6a-6162-44fa-9aef-13b0c98d647f');
  await page.getByRole('spinbutton', { name: 'Travel Allowance (₹)' }).click();
  await page.getByRole('spinbutton', { name: 'Travel Allowance (₹)' }).press('ControlOrMeta+Shift+_');
  await page.getByRole('spinbutton', { name: 'Travel Allowance (₹)' }).press('ControlOrMeta+Shift+_');
  await page.getByRole('spinbutton', { name: 'Travel Allowance (₹)' }).press('ControlOrMeta+Shift+_');
  await page.getByRole('spinbutton', { name: 'Travel Allowance (₹)' }).press('ControlOrMeta+Shift+_');
  await page.getByRole('spinbutton', { name: 'Travel Allowance (₹)' }).press('ControlOrMeta+Shift+_');
  await page.getByRole('spinbutton', { name: 'Travel Allowance (₹)' }).press('ControlOrMeta+Shift+_');
  await page.getByRole('spinbutton', { name: 'Travel Allowance (₹)' }).press('ControlOrMeta+Shift+_');
  await page.getByRole('spinbutton', { name: 'Travel Allowance (₹)' }).press('ControlOrMeta+Shift+_');
  await page.getByRole('dialog', { name: 'Create New Beat' }).click();
  await page.getByRole('dialog', { name: 'Create New Beat' }).press('ControlOrMeta+Shift+_');
  await page.getByRole('dialog', { name: 'Create New Beat' }).press('ControlOrMeta+Shift+_');
  await page.getByRole('dialog', { name: 'Create New Beat' }).press('ControlOrMeta+Shift+_');
  await page.getByRole('dialog', { name: 'Create New Beat' }).press('ControlOrMeta+Shift+_');
  await page.getByRole('dialog', { name: 'Create New Beat' }).press('ControlOrMeta+-');
  await page.getByRole('dialog', { name: 'Create New Beat' }).press('ControlOrMeta+-');
  await page.getByRole('dialog', { name: 'Create New Beat' }).press('ControlOrMeta+-');
  await page.getByRole('dialog', { name: 'Create New Beat' }).press('ControlOrMeta+-');
  await page.getByRole('heading', { name: 'Create New Beat' }).click();
  await page.getByRole('button', { name: 'Add it for the day Beat will' }).click();
});