/**
 * Phase 3 + Phase 5: Blank import template with sample rows + legend sheet.
 * One template imports BOTH base products AND variants:
 *   - Leave `parent_sku` blank  → row is a base product.
 *   - Fill `parent_sku`         → row is a variant of that product.
 *     Blank override cells on a variant row mean "inherit from parent".
 */
import * as XLSX from 'xlsx';
import { downloadExcel } from '@/utils/fileDownloader';

export const IMPORT_HEADERS = [
  'sku*',
  'parent_sku',
  'variant_name',
  'name*',
  'description',
  'brand',
  'category*',
  'product_type',
  'gst_percentage*',
  'hsn_code',
  'tax_master',
  'rate*',
  'base_unit*',
  'price_basis_unit*',
  'default_sales_unit*',
  'unit_1',
  'unit_1_factor',
  'unit_2',
  'unit_2_factor',
  'unit_3',
  'unit_3_factor',
  'opening_stock',
  'reorder_level',
  'reorder_quantity',
  'net_weight_g',
  'net_volume_ml',
  'standard_cost',
  'manufacturer',
  'country_of_origin',
  'sku_image_url',
  'image_file',
  'is_active',
  'is_discontinued',
] as const;

// Strip the trailing "*" used to mark mandatory headers.
export const cleanHeader = (h: string) => h.replace(/\*$/, '').trim().toLowerCase();

export async function downloadProductImportTemplate(): Promise<void> {
  const sampleRows = [
    {
      'sku*': 'COFFEE01',
      parent_sku: '',
      variant_name: '',
      'name*': 'British Coffee 250g',
      description: 'Instant filter coffee',
      brand: 'British',
      'category*': 'Beverages',
      product_type: 'finished_good',
      'gst_percentage*': 5,
      hsn_code: '21011200',
      tax_master: 'GST 5%',
      'rate*': 240,
      'base_unit*': 'PIECE',
      'price_basis_unit*': 'PIECE',
      'default_sales_unit*': 'PIECE',
      unit_1: 'BOX',
      unit_1_factor: 24,
      unit_2: 'CARTON',
      unit_2_factor: 144,
      unit_3: '',
      unit_3_factor: '',
      opening_stock: 0,
      reorder_level: 10,
      reorder_quantity: 50,
      net_weight_g: 250,
      net_volume_ml: '',
      standard_cost: 180,
      manufacturer: 'British Foods Pvt Ltd',
      country_of_origin: 'India',
      sku_image_url: '',
      image_file: 'COFFEE01.jpg',
      is_active: 'yes',
      is_discontinued: 'no',
    },
    {
      'sku*': 'COFFEE01-500',
      parent_sku: 'COFFEE01',
      variant_name: '500g Pack',
      'name*': '',
      description: '',
      brand: '',
      'category*': '',
      product_type: '',
      'gst_percentage*': '',
      hsn_code: '',
      tax_master: '',
      'rate*': 460,
      'base_unit*': '',
      'price_basis_unit*': '',
      'default_sales_unit*': '',
      unit_1: '',
      unit_1_factor: '',
      unit_2: '',
      unit_2_factor: '',
      unit_3: '',
      unit_3_factor: '',
      opening_stock: 0,
      reorder_level: '',
      reorder_quantity: '',
      net_weight_g: 500,
      net_volume_ml: '',
      standard_cost: '',
      manufacturer: '',
      country_of_origin: '',
      sku_image_url: '',
      image_file: 'COFFEE01-500.jpg',
      is_active: 'yes',
      is_discontinued: 'no',
    },
    {
      'sku*': 'SUGAR1KG',
      parent_sku: '',
      variant_name: '',
      'name*': 'White Sugar 1kg',
      description: 'Refined white sugar',
      brand: 'Generic',
      'category*': 'Groceries',
      product_type: 'finished_good',
      'gst_percentage*': 5,
      hsn_code: '17019100',
      tax_master: '',
      'rate*': 45,
      'base_unit*': 'GRAM',
      'price_basis_unit*': 'KG',
      'default_sales_unit*': 'KG',
      unit_1: 'BAG',
      unit_1_factor: 30,
      unit_2: '',
      unit_2_factor: '',
      unit_3: '',
      unit_3_factor: '',
      opening_stock: 0,
      reorder_level: 50,
      reorder_quantity: '',
      net_weight_g: 1000,
      net_volume_ml: '',
      standard_cost: '',
      manufacturer: '',
      country_of_origin: '',
      sku_image_url: '',
      image_file: 'SUGAR1KG.jpg',
      is_active: 'yes',
      is_discontinued: 'no',
    },
  ];

  const ws = XLSX.utils.json_to_sheet(sampleRows, { header: IMPORT_HEADERS as unknown as string[] });
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Products');

  const legend: (string | number)[][] = [
    ['Column', 'Mandatory', 'Description'],
    ['sku', 'YES', 'Unique SKU; upsert key (for both products and variants).'],
    ['parent_sku', 'no', 'FILL THIS TO MAKE THE ROW A VARIANT. Must match an existing product SKU or a base row earlier in this file. Leave blank for a base product.'],
    ['variant_name', 'depends', 'Required when parent_sku is filled (e.g. "500g Pack", "Red", "Family Size").'],
    ['name', 'YES for products', 'Product display name. Ignored for variant rows.'],
    ['description', 'no', 'Long description. On a variant row, blank = inherit from parent.'],
    ['brand', 'no', 'Brand name. On a variant row, blank = inherit from parent.'],
    ['category', 'YES for products', 'Category name (auto-created if new). On variant rows, blank = inherit.'],
    ['product_type', 'no', 'e.g. finished_good, raw_material. Variant: blank = inherit.'],
    ['gst_percentage', 'YES for products', '0–100. Used for tax display. Variant: blank = inherit.'],
    ['hsn_code', 'no', 'HSN/SAC code. Variant: blank = inherit.'],
    ['tax_master', 'no', 'Tax Master name (must exist). Variant: blank = inherit.'],
    ['rate', 'YES for products', 'Selling price for the price_basis_unit. Variant: optional; sets variant price.'],
    ['base_unit / price_basis_unit / default_sales_unit', 'YES for products', 'See two-tier UOM rule below. Variant: blank = inherit.'],
    ['unit_1 / unit_2 / unit_3 (+ _factor)', 'no', 'Additional UOM mappings for the base product only. Ignored on variant rows.'],
    ['opening_stock / reorder_level / reorder_quantity', 'no', 'Numeric. Variant: blank = inherit (except stock_quantity which is stored on the variant).'],
    ['net_weight_g', 'no', 'Required for weight-based products. Variant: blank = inherit.'],
    ['net_volume_ml', 'no', 'Required for volume-based products. Variant: blank = inherit.'],
    ['standard_cost', 'no', 'Numeric. Variant: blank = inherit.'],
    ['manufacturer / country_of_origin', 'no', 'Variant: blank = inherit.'],
    ['sku_image_url', 'no', 'Direct image URL. Variant: blank = inherit (falls back to base image).'],
    ['image_file', 'no', 'Filename reference; upload images on the Images tab (filename minus extension = SKU).'],
    ['is_active', 'no', 'yes/no. Defaults to yes.'],
    ['is_discontinued', 'no', 'yes/no. Defaults to no (products only).'],
    [],
    ['Variants', '', ''],
    ['How it works', '', 'A variant inherits every field that is BLANK in its row from its parent product. Filled cells become overrides. Blank tax/category cells stay NULL; the app resolves them from the parent at read time.'],
    [],
    ['Two-tier UOM rule', '', ''],
    ['Dimensional (Weight/Volume/Length)', '', 'Conversion is physics and set ONCE in the Unit Master (e.g. KG=1000g, LITRE=1000ml). Leave unit_n_factor blank.'],
    ['Pack / Count (Quantity, Packaging, Medication, Electronics)', '', 'Conversion is per-product (1 BOX = 24 for product A, 12 for product B). Always provide unit_n_factor.'],
  ];
  const wsLegend = XLSX.utils.aoa_to_sheet(legend);
  XLSX.utils.book_append_sheet(wb, wsLegend, 'Legend');

  const date = new Date().toISOString().slice(0, 10);
  await downloadExcel(wb, `products_import_template_${date}.xlsx`, XLSX);
}
