// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { QA_MIRRORED_TABLES, QA_SAFE_RPCS, isQAMode, qaTablePrefix } from '@/lib/tableRouter';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const rawClient = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
});

/**
 * QA-mode safeguards for the Supabase client.
 *
 * - In production builds this wrapper is a no-op: `supabase` IS the raw client.
 * - In QA builds (VITE_APP_MODE === 'qa'):
 *     • `from('retailers')` etc. for mirrored tables → `from('qa_retailers')`.
 *     • Writes (insert/update/upsert/delete) on non-mirrored tables are blocked.
 *     • `rpc(name, ...)` is blocked unless `name` is in QA_SAFE_RPCS.
 *   This prevents the QA APK from silently polluting production data.
 */
function buildQAClient(client: SupabaseClient<Database>): SupabaseClient<Database> {
  const prefix = qaTablePrefix();

  const blockedWriteError = (table: string) => {
    const msg = `[QA] Write to non-mirrored table "${table}" is blocked. Add it to QA_MIRRORED_TABLES (with a qa_${table} migration) to enable.`;
    // eslint-disable-next-line no-console
    console.error(msg, new Error('blocked QA write').stack);
    const err = { message: msg, details: '', hint: '', code: 'QA_BLOCKED' };
    return { data: null, error: err, count: null, status: 403, statusText: 'QA blocked' };
  };

  const wrapBuilder = (builder: any, originalTable: string, isMirrored: boolean) => {
    if (isMirrored) return builder;
    // Only need to guard write methods on the initial builder.
    const writeMethods = ['insert', 'update', 'upsert', 'delete'] as const;
    return new Proxy(builder, {
      get(target, prop, receiver) {
        if (typeof prop === 'string' && (writeMethods as readonly string[]).includes(prop)) {
          return (..._args: any[]) => {
            const blocked = blockedWriteError(originalTable);
            // Return a thenable so `await supabase.from(x).insert(...)` resolves with an error.
            return {
              ...blocked,
              select: () => ({
                ...blocked,
                single: () => Promise.resolve(blocked),
                maybeSingle: () => Promise.resolve(blocked),
                then: (resolve: any) => Promise.resolve(blocked).then(resolve),
              }),
              single: () => Promise.resolve(blocked),
              maybeSingle: () => Promise.resolve(blocked),
              then: (resolve: any) => Promise.resolve(blocked).then(resolve),
            };
          };
        }
        return Reflect.get(target, prop, receiver);
      },
    });
  };

  return new Proxy(client, {
    get(target, prop, receiver) {
      if (prop === 'from') {
        return (name: string) => {
          const isMirrored = QA_MIRRORED_TABLES.has(name);
          const routedName = isMirrored ? `${prefix}${name}` : name;
          const builder = (target as any).from(routedName);
          return wrapBuilder(builder, name, isMirrored);
        };
      }
      if (prop === 'rpc') {
        return (name: string, args?: any, options?: any) => {
          if (!QA_SAFE_RPCS.has(name)) {
            const msg = `[QA] RPC "${name}" is blocked in QA build. Add it to QA_SAFE_RPCS once a qa-safe version exists.`;
            // eslint-disable-next-line no-console
            console.error(msg, new Error('blocked QA rpc').stack);
            const err = { message: msg, details: '', hint: '', code: 'QA_BLOCKED' };
            return Promise.resolve({ data: null, error: err, count: null, status: 403, statusText: 'QA blocked' }) as any;
          }
          return (target as any).rpc(name, args, options);
        };
      }
      return Reflect.get(target, prop, receiver);
    },
  });
}

export const supabase: SupabaseClient<Database> = isQAMode()
  ? buildQAClient(rawClient)
  : rawClient;
